version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - /c/Users/User/Desktop:/shared_data
    networks:
      - mynetwork

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/User/Desktop:/shared_data
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
  
  nodejs:
    build:
      context: ./server  # 當前目錄
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # 映射 HTTP 端口
      - "3002:3002"  # 映射 WebSocket 端口
    networks:
      - mynetwork
    volumes:
      - ./server:/app  # 仍然掛載程式碼
      - /app/node_modules  # 讓 node_modules 存在於容器內，不受覆蓋


volumes:
  sqlserver_data:
  jenkins_home:
  grafana_data:

networks:
  mynetwork: